/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module ControlUnit (
  input clk,
  output Inst_Fetch,
  output Inst_Decode,
  output Inst_Execute,
  output Write_back
);
  wire Inst_Execute_temp;
  wire Write_back_temp;
  wire Inst_Decode_temp;
  wire Inst_Fetch_temp;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( Inst_Execute_temp ),
    .C( clk ),
    .Q( Write_back_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( Inst_Decode_temp ),
    .C( clk ),
    .Q( Inst_Execute_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( Inst_Fetch_temp ),
    .C( clk ),
    .Q( Inst_Decode_temp )
  );
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i3 (
    .D( Write_back_temp ),
    .C( clk ),
    .Q( Inst_Fetch_temp )
  );
  assign Inst_Fetch = Inst_Fetch_temp;
  assign Inst_Decode = Inst_Decode_temp;
  assign Inst_Execute = Inst_Execute_temp;
  assign Write_back = Write_back_temp;
endmodule

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \1_bit_full_adder  (
  input A,
  input B,
  input C,
  output sum,
  output Carry_out
);
  wire s0;
  wire s1;
  assign s0 = ~ B;
  assign s1 = ~ C;
  assign sum = ((~ A & s0 & C) | (~ A & B & s1) | (A & s0 & s1) | (A & B & C));
  assign Carry_out = ((B & C) | (A & s0 & C) | (A & B & s1));
endmodule

module \8BitAdder  (
  input [7:0] A,
  input [7:0] B,
  input Carry_in,
  output [7:0] Sum,
  output Carry_out
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  assign s25 = A[0];
  assign s17 = A[1];
  assign s0 = A[2];
  assign s5 = A[3];
  assign s9 = A[4];
  assign s13 = A[5];
  assign s21 = A[6];
  assign s28 = A[7];
  assign s26 = B[0];
  assign s18 = B[1];
  assign s1 = B[2];
  assign s6 = B[3];
  assign s10 = B[4];
  assign s14 = B[5];
  assign s22 = B[6];
  assign s29 = B[7];
  \1_bit_full_adder  \1_bit_full_adder_i0 (
    .A( s25 ),
    .B( s26 ),
    .C( Carry_in ),
    .sum( s27 ),
    .Carry_out( s19 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i1 (
    .A( s17 ),
    .B( s18 ),
    .C( s19 ),
    .sum( s20 ),
    .Carry_out( s2 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i2 (
    .A( s0 ),
    .B( s1 ),
    .C( s2 ),
    .sum( s3 ),
    .Carry_out( s4 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i3 (
    .A( s5 ),
    .B( s6 ),
    .C( s4 ),
    .sum( s7 ),
    .Carry_out( s8 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i4 (
    .A( s9 ),
    .B( s10 ),
    .C( s8 ),
    .sum( s11 ),
    .Carry_out( s12 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i5 (
    .A( s13 ),
    .B( s14 ),
    .C( s12 ),
    .sum( s15 ),
    .Carry_out( s16 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i6 (
    .A( s21 ),
    .B( s22 ),
    .C( s16 ),
    .sum( s23 ),
    .Carry_out( s24 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i7 (
    .A( s28 ),
    .B( s29 ),
    .C( s24 ),
    .sum( s30 ),
    .Carry_out( Carry_out )
  );
  assign Sum[0] = s27;
  assign Sum[1] = s20;
  assign Sum[2] = s3;
  assign Sum[3] = s7;
  assign Sum[4] = s11;
  assign Sum[5] = s15;
  assign Sum[6] = s23;
  assign Sum[7] = s30;
endmodule

module \8bit_PC  (
  input CLK,
  input [7:0] Inc_by,
  input [1:0] CTRL, // 00-> Load
                    // 01-> INC
                    // 10-> Clear
                    // 11-> Set FF
  output [7:0] \Output 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [7:0] s16;
  wire [7:0] Output_temp;
  wire [7:0] s17;
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( CTRL ),
    .in_0( Output_temp ),
    .in_1( s17 ),
    .in_2( 8'b0 ),
    .in_3( 8'b11111111 ),
    .out( s16 )
  );
  \8BitAdder  \8BitAdder_i1 (
    .A( Output_temp ),
    .B( Inc_by ),
    .Carry_in( 1'b0 ),
    .Sum( s17 )
  );
  assign s14 = s16[0];
  assign s12 = s16[1];
  assign s0 = s16[2];
  assign s2 = s16[3];
  assign s4 = s16[4];
  assign s6 = s16[5];
  assign s8 = s16[6];
  assign s10 = s16[7];
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s2 ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s4 ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s8 ),
    .C( CLK ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s10 ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( s12 ),
    .C( CLK ),
    .Q( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s14 ),
    .C( CLK ),
    .Q( s15 )
  );
  assign Output_temp[0] = s15;
  assign Output_temp[1] = s13;
  assign Output_temp[2] = s1;
  assign Output_temp[3] = s3;
  assign Output_temp[4] = s5;
  assign Output_temp[5] = s7;
  assign Output_temp[6] = s9;
  assign Output_temp[7] = s11;
  assign \Output  = Output_temp;
endmodule

module Decoder3 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel
);
    assign out_0 = (sel == 3'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 3'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 3'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 3'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 3'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 3'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 3'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 3'h7)? 1'b1 : 1'b0;
endmodule


module \8_bit  (
  input CLK,
  input [7:0] \Input ,
  input [1:0] CTRL, // 00-> Load
                    // 01-> Store
                    // 10-> Clear
                    // 11-> Set FF
  output [7:0] \Output 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [7:0] s16;
  wire [7:0] Output_temp;
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( CTRL ),
    .in_0( Output_temp ),
    .in_1( \Input  ),
    .in_2( 8'b0 ),
    .in_3( 8'b11111111 ),
    .out( s16 )
  );
  assign s14 = s16[0];
  assign s12 = s16[1];
  assign s0 = s16[2];
  assign s2 = s16[3];
  assign s4 = s16[4];
  assign s6 = s16[5];
  assign s8 = s16[6];
  assign s10 = s16[7];
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s2 ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s4 ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s8 ),
    .C( CLK ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s10 ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s12 ),
    .C( CLK ),
    .Q( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( s14 ),
    .C( CLK ),
    .Q( s15 )
  );
  assign Output_temp[0] = s15;
  assign Output_temp[1] = s13;
  assign Output_temp[2] = s1;
  assign Output_temp[3] = s3;
  assign Output_temp[4] = s5;
  assign Output_temp[5] = s7;
  assign Output_temp[6] = s9;
  assign Output_temp[7] = s11;
  assign \Output  = Output_temp;
endmodule

module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \8B_Memory  (
  input [2:0] Address_pin,
  input clk,
  input [7:0] Data_input,
  input [1:0] CTRL,
  output [7:0] Data_output
);
  wire s0;
  wire [7:0] s1;
  wire s2;
  wire [7:0] s3;
  wire s4;
  wire [7:0] s5;
  wire s6;
  wire [7:0] s7;
  wire s8;
  wire [7:0] s9;
  wire s10;
  wire [7:0] s11;
  wire s12;
  wire [7:0] s13;
  wire s14;
  wire [7:0] s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  Decoder3 Decoder3_i0 (
    .sel( Address_pin ),
    .out_0( s16 ),
    .out_1( s17 ),
    .out_2( s18 ),
    .out_3( s19 ),
    .out_4( s20 ),
    .out_5( s21 ),
    .out_6( s22 ),
    .out_7( s23 )
  );
  assign s10 = (clk & s16);
  assign s12 = (clk & s17);
  assign s14 = (clk & s18);
  assign s0 = (clk & s19);
  assign s2 = (clk & s20);
  assign s4 = (clk & s21);
  assign s6 = (clk & s22);
  assign s8 = (clk & s23);
  \8_bit  \8_bit_i1 (
    .CLK( s0 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s1 )
  );
  \8_bit  \8_bit_i2 (
    .CLK( s2 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s3 )
  );
  \8_bit  \8_bit_i3 (
    .CLK( s4 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s5 )
  );
  \8_bit  \8_bit_i4 (
    .CLK( s6 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s7 )
  );
  \8_bit  \8_bit_i5 (
    .CLK( s8 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s9 )
  );
  \8_bit  \8_bit_i6 (
    .CLK( s10 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s11 )
  );
  \8_bit  \8_bit_i7 (
    .CLK( s12 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s13 )
  );
  \8_bit  \8_bit_i8 (
    .CLK( s14 ),
    .\Input ( Data_input ),
    .CTRL( CTRL ),
    .\Output ( s15 )
  );
  Mux_8x1_NBits #(
    .Bits(8)
  )
  Mux_8x1_NBits_i9 (
    .sel( Address_pin ),
    .in_0( s11 ),
    .in_1( s13 ),
    .in_2( s15 ),
    .in_3( s1 ),
    .in_4( s3 ),
    .in_5( s5 ),
    .in_6( s7 ),
    .in_7( s9 ),
    .out( Data_output )
  );
endmodule

module \8_bit_IR  (
  input CLK,
  input [7:0] \Input ,
  input [1:0] CTRL, // 00-> Load
                    // 01-> Store
                    // 10-> Clear
                    // 11-> Set FF
  output [7:0] \Output 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [7:0] s16;
  wire [7:0] Output_temp;
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( CTRL ),
    .in_0( Output_temp ),
    .in_1( \Input  ),
    .in_2( 8'b0 ),
    .in_3( 8'b11111111 ),
    .out( s16 )
  );
  assign s14 = s16[0];
  assign s12 = s16[1];
  assign s0 = s16[2];
  assign s2 = s16[3];
  assign s4 = s16[4];
  assign s6 = s16[5];
  assign s8 = s16[6];
  assign s10 = s16[7];
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s2 ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s4 ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s8 ),
    .C( CLK ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s10 ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s12 ),
    .C( CLK ),
    .Q( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( s14 ),
    .C( CLK ),
    .Q( s15 )
  );
  assign Output_temp[0] = s15;
  assign Output_temp[1] = s13;
  assign Output_temp[2] = s1;
  assign Output_temp[3] = s3;
  assign Output_temp[4] = s5;
  assign Output_temp[5] = s7;
  assign Output_temp[6] = s9;
  assign Output_temp[7] = s11;
  assign \Output  = Output_temp;
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DemuxBus2
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    output [(Bits-1):0] out_2,
    output [(Bits-1):0] out_3,
    input [1:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 2'h0)? in : Default;
    assign out_1 = (sel == 2'h1)? in : Default;
    assign out_2 = (sel == 2'h2)? in : Default;
    assign out_3 = (sel == 2'h3)? in : Default;
endmodule


module RegisterFile (
  input clk,
  input [1:0] Read_Register1,
  input [1:0] Read_Register2,
  input [7:0] Write_data,
  input [1:0] Write_Register,
  input [7:0] ctrl,
  output [7:0] Read_Data1,
  output [7:0] Read_Data2
);
  wire [7:0] s0;
  wire [1:0] s1;
  wire [7:0] s2;
  wire [7:0] s3;
  wire [1:0] s4;
  wire [7:0] s5;
  wire [7:0] s6;
  wire [1:0] s7;
  wire [7:0] s8;
  wire [7:0] s9;
  wire [1:0] s10;
  wire [7:0] s11;
  DemuxBus2 #(
    .Bits(8),
    .Default(0)
  )
  DemuxBus2_i0 (
    .sel( Write_Register ),
    .in( Write_data ),
    .out_0( s0 ),
    .out_1( s3 ),
    .out_2( s6 ),
    .out_3( s9 )
  );
  assign s1 = ctrl[1:0];
  assign s4 = ctrl[3:2];
  assign s7 = ctrl[5:4];
  assign s10 = ctrl[7:6];
  // R0
  \8_bit  \8_bit_i1 (
    .CLK( clk ),
    .\Input ( s0 ),
    .CTRL( s1 ),
    .\Output ( s2 )
  );
  // R1
  \8_bit  \8_bit_i2 (
    .CLK( clk ),
    .\Input ( s3 ),
    .CTRL( s4 ),
    .\Output ( s5 )
  );
  // R2
  \8_bit  \8_bit_i3 (
    .CLK( clk ),
    .\Input ( s6 ),
    .CTRL( s7 ),
    .\Output ( s8 )
  );
  // R3
  \8_bit  \8_bit_i4 (
    .CLK( clk ),
    .\Input ( s9 ),
    .CTRL( s10 ),
    .\Output ( s11 )
  );
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i5 (
    .sel( Read_Register1 ),
    .in_0( s2 ),
    .in_1( s5 ),
    .in_2( s8 ),
    .in_3( s11 ),
    .out( Read_Data1 )
  );
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i6 (
    .sel( Read_Register2 ),
    .in_0( s2 ),
    .in_1( s5 ),
    .in_2( s8 ),
    .in_3( s11 ),
    .out( Read_Data2 )
  );
endmodule

module \8bitAdder2026  (
  input [7:0] A,
  input [7:0] Y,
  input Carry_in,
  output Carry_out,
  output [7:0] Sum
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  assign s17 = A[0];
  assign s13 = A[1];
  assign s9 = A[2];
  assign s5 = A[3];
  assign s0 = A[4];
  assign s28 = A[5];
  assign s24 = A[6];
  assign s20 = A[7];
  assign s18 = Y[0];
  assign s14 = Y[1];
  assign s10 = Y[2];
  assign s6 = Y[3];
  assign s1 = Y[4];
  assign s29 = Y[5];
  assign s25 = Y[6];
  assign s21 = Y[7];
  \1_bit_full_adder  \1_bit_full_adder_i0 (
    .A( s17 ),
    .B( s18 ),
    .C( Carry_in ),
    .sum( s19 ),
    .Carry_out( s15 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i1 (
    .A( s13 ),
    .B( s14 ),
    .C( s15 ),
    .sum( s16 ),
    .Carry_out( s11 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i2 (
    .A( s9 ),
    .B( s10 ),
    .C( s11 ),
    .sum( s12 ),
    .Carry_out( s7 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i3 (
    .A( s5 ),
    .B( s6 ),
    .C( s7 ),
    .sum( s8 ),
    .Carry_out( s2 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i4 (
    .A( s0 ),
    .B( s1 ),
    .C( s2 ),
    .sum( s3 ),
    .Carry_out( s4 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i5 (
    .A( s28 ),
    .B( s29 ),
    .C( s4 ),
    .sum( s30 ),
    .Carry_out( s26 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i6 (
    .A( s24 ),
    .B( s25 ),
    .C( s26 ),
    .sum( s27 ),
    .Carry_out( s22 )
  );
  \1_bit_full_adder  \1_bit_full_adder_i7 (
    .A( s20 ),
    .B( s21 ),
    .C( s22 ),
    .sum( s23 ),
    .Carry_out( Carry_out )
  );
  assign Sum[0] = s19;
  assign Sum[1] = s16;
  assign Sum[2] = s12;
  assign Sum[3] = s8;
  assign Sum[4] = s3;
  assign Sum[5] = s30;
  assign Sum[6] = s27;
  assign Sum[7] = s23;
endmodule

module \8bitALU  (
  input [7:0] A,
  input [2:0] S_1_S_0_Carry_in,
  input [7:0] B,
  output [7:0] \Output ,
  output Status
);
  wire [7:0] s0;
  wire s1;
  wire [1:0] s2;
  wire [7:0] s3;
  wire [7:0] const8b0;
  wire [7:0] s4;
  assign const8b0 = 8'b0;
  assign s3 = ~ B;
  assign s4 = ~ const8b0;
  assign s1 = S_1_S_0_Carry_in[0];
  assign s2 = S_1_S_0_Carry_in[2:1];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( s2 ),
    .in_0( B ),
    .in_1( s3 ),
    .in_2( const8b0 ),
    .in_3( s4 ),
    .out( s0 )
  );
  \8bitAdder2026  \8bitAdder2026_i1 (
    .A( A ),
    .Y( s0 ),
    .Carry_in( s1 ),
    .Carry_out( Status ),
    .Sum( \Output  )
  );
endmodule

module \8BitProcessor  (
  input clk,
  input [7:0] InstrMem_input,
  input [1:0] InstrMem_ctrl,
  output [7:0] IR_output,
  output Inst_Fetch,
  output Inst_decode,
  output Inst_exec,
  output Write_Back,
  output [2:0] Program_Counter,
  output [1:0] IR_ctrl,
  output [7:0] RegFile_ctrl,
  output [7:0] ALU_output
);
  wire [1:0] s0;
  wire [1:0] s1;
  wire [7:0] ALU_output_temp;
  wire [7:0] RegFile_ctrl_temp;
  wire [7:0] s2;
  wire [7:0] s3;
  wire [7:0] s4;
  wire [2:0] s5;
  wire [2:0] Program_Counter_temp;
  wire [7:0] s6;
  wire [1:0] s7;
  wire [7:0] s8;
  wire [1:0] IR_ctrl_temp;
  wire [7:0] IR_output_temp;
  wire s9;
  wire Inst_Fetch_temp;
  wire Write_Back_temp;
  wire s10;
  wire [7:0] s11;
  wire [7:0] s12;
  wire s13;
  ControlUnit ControlUnit_i0 (
    .clk( clk ),
    .Inst_Fetch( Inst_Fetch_temp ),
    .Inst_Decode( Inst_decode ),
    .Inst_Execute( Inst_exec ),
    .Write_back( Write_Back_temp )
  );
  assign s13 = InstrMem_ctrl[0];
  assign s7[0] = Write_Back_temp;
  assign s7[1] = 1'b0;
  Mux_2x1 Mux_2x1_i1 (
    .sel( s13 ),
    .in_0( Inst_Fetch_temp ),
    .in_1( 1'b0 ),
    .out( s10 )
  );
  \8bit_PC  \8bit_PC_i2 (
    .CLK( clk ),
    .Inc_by( 8'b1 ),
    .CTRL( s7 ),
    .\Output ( s8 )
  );
  assign IR_ctrl_temp[0] = s10;
  assign IR_ctrl_temp[1] = 1'b0;
  assign Program_Counter_temp = s8[2:0];
  \8B_Memory  \8B_Memory_i3 (
    .Address_pin( Program_Counter_temp ),
    .clk( clk ),
    .Data_input( InstrMem_input ),
    .CTRL( InstrMem_ctrl ),
    .Data_output( s6 )
  );
  \8_bit_IR  \8_bit_IR_i4 (
    .CLK( clk ),
    .\Input ( s6 ),
    .CTRL( IR_ctrl_temp ),
    .\Output ( IR_output_temp )
  );
  assign s9 = IR_output_temp[0];
  assign s1 = IR_output_temp[2:1];
  assign s0 = IR_output_temp[4:3];
  assign s5 = IR_output_temp[7:5];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i5 (
    .sel( s0 ),
    .in_0( 8'b1 ),
    .in_1( 8'b100 ),
    .in_2( 8'b10000 ),
    .in_3( 8'b1000000 ),
    .out( s11 )
  );
  assign s12[1:0] = s1;
  assign s12[7:2] = 6'b0;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i6 (
    .sel( Write_Back_temp ),
    .in_0( 8'b0 ),
    .in_1( s11 ),
    .out( RegFile_ctrl_temp )
  );
  RegisterFile RegisterFile_i7 (
    .clk( clk ),
    .Read_Register1( s0 ),
    .Read_Register2( s1 ),
    .Write_data( ALU_output_temp ),
    .Write_Register( s0 ),
    .ctrl( RegFile_ctrl_temp ),
    .Read_Data1( s2 ),
    .Read_Data2( s3 )
  );
  \8bitALU  \8bitALU_i8 (
    .A( s4 ),
    .S_1_S_0_Carry_in( s5 ),
    .B( s3 ),
    .\Output ( ALU_output_temp )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i9 (
    .sel( s9 ),
    .in_0( s2 ),
    .in_1( s12 ),
    .out( s4 )
  );
  assign IR_output = IR_output_temp;
  assign Inst_Fetch = Inst_Fetch_temp;
  assign Write_Back = Write_Back_temp;
  assign Program_Counter = Program_Counter_temp;
  assign IR_ctrl = IR_ctrl_temp;
  assign RegFile_ctrl = RegFile_ctrl_temp;
  assign ALU_output = ALU_output_temp;
endmodule
