-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_D_FF is
  generic (
    Default: std_logic ); 
  port ( D  : in std_logic;
         C  : in std_logic;
         Q  : out std_logic;
         notQ : out std_logic );
end DIG_D_FF;

architecture Behavioral of DIG_D_FF is
   signal state : std_logic := Default;
begin
   Q    <= state;
   notQ <= NOT( state );

   process(C)
   begin
      if rising_edge(C) then
        state  <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity ControlUnit is
  port (
    clk: in std_logic;
    Inst_Fetch: out std_logic;
    Inst_Decode: out std_logic;
    Inst_Execute: out std_logic;
    Write_back: out std_logic);
end ControlUnit;

architecture Behavioral of ControlUnit is
  signal Inst_Execute_temp: std_logic;
  signal Write_back_temp: std_logic;
  signal Inst_Decode_temp: std_logic;
  signal Inst_Fetch_temp: std_logic;
begin
  gate0: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => Inst_Execute_temp,
      C => clk,
      Q => Write_back_temp);
  gate1: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => Inst_Decode_temp,
      C => clk,
      Q => Inst_Execute_temp);
  gate2: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => Inst_Fetch_temp,
      C => clk,
      Q => Inst_Decode_temp);
  gate3: entity work.DIG_D_FF
    generic map (
      Default => '1')
    port map (
      D => Write_back_temp,
      C => clk,
      Q => Inst_Fetch_temp);
  Inst_Fetch <= Inst_Fetch_temp;
  Inst_Decode <= Inst_Decode_temp;
  Inst_Execute <= Inst_Execute_temp;
  Write_back <= Write_back_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1_bit_full_adder is
  port (
    A: in std_logic;
    B: in std_logic;
    C: in std_logic;
    sum: out std_logic;
    Carry_out: out std_logic);
end n1_bit_full_adder;

architecture Behavioral of n1_bit_full_adder is
  signal s0: std_logic;
  signal s1: std_logic;
begin
  s0 <= NOT B;
  s1 <= NOT C;
  sum <= ((NOT A AND s0 AND C) OR (NOT A AND B AND s1) OR (A AND s0 AND s1) OR (A AND B AND C));
  Carry_out <= ((B AND C) OR (A AND s0 AND C) OR (A AND B AND s1));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8BitAdder is
  port (
    A: in std_logic_vector(7 downto 0);
    B: in std_logic_vector(7 downto 0);
    Carry_in: in std_logic;
    Sum: out std_logic_vector(7 downto 0);
    Carry_out: out std_logic);
end n8BitAdder;

architecture Behavioral of n8BitAdder is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
begin
  s25 <= A(0);
  s17 <= A(1);
  s0 <= A(2);
  s5 <= A(3);
  s9 <= A(4);
  s13 <= A(5);
  s21 <= A(6);
  s28 <= A(7);
  s26 <= B(0);
  s18 <= B(1);
  s1 <= B(2);
  s6 <= B(3);
  s10 <= B(4);
  s14 <= B(5);
  s22 <= B(6);
  s29 <= B(7);
  gate0: entity work.n1_bit_full_adder
    port map (
      A => s25,
      B => s26,
      C => Carry_in,
      sum => s27,
      Carry_out => s19);
  gate1: entity work.n1_bit_full_adder
    port map (
      A => s17,
      B => s18,
      C => s19,
      sum => s20,
      Carry_out => s2);
  gate2: entity work.n1_bit_full_adder
    port map (
      A => s0,
      B => s1,
      C => s2,
      sum => s3,
      Carry_out => s4);
  gate3: entity work.n1_bit_full_adder
    port map (
      A => s5,
      B => s6,
      C => s4,
      sum => s7,
      Carry_out => s8);
  gate4: entity work.n1_bit_full_adder
    port map (
      A => s9,
      B => s10,
      C => s8,
      sum => s11,
      Carry_out => s12);
  gate5: entity work.n1_bit_full_adder
    port map (
      A => s13,
      B => s14,
      C => s12,
      sum => s15,
      Carry_out => s16);
  gate6: entity work.n1_bit_full_adder
    port map (
      A => s21,
      B => s22,
      C => s16,
      sum => s23,
      Carry_out => s24);
  gate7: entity work.n1_bit_full_adder
    port map (
      A => s28,
      B => s29,
      C => s24,
      sum => s30,
      Carry_out => Carry_out);
  Sum(0) <= s27;
  Sum(1) <= s20;
  Sum(2) <= s3;
  Sum(3) <= s7;
  Sum(4) <= s11;
  Sum(5) <= s15;
  Sum(6) <= s23;
  Sum(7) <= s30;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8bit_PC is
  port (
    CLK: in std_logic;
    Inc_by: in std_logic_vector(7 downto 0);
    CTRL: in std_logic_vector(1 downto 0); -- 00-> Load
                                           -- 01-> INC
                                           -- 10-> Clear
                                           -- 11-> Set FF
    Output: out std_logic_vector(7 downto 0));
end n8bit_PC;

architecture Behavioral of n8bit_PC is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic_vector(7 downto 0);
  signal Output_temp: std_logic_vector(7 downto 0);
  signal s17: std_logic_vector(7 downto 0);
begin
  gate0: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => CTRL,
      in_0 => Output_temp,
      in_1 => s17,
      in_2 => "00000000",
      in_3 => "11111111",
      p_out => s16);
  gate1: entity work.n8BitAdder
    port map (
      A => Output_temp,
      B => Inc_by,
      Carry_in => '0',
      Sum => s17);
  s14 <= s16(0);
  s12 <= s16(1);
  s0 <= s16(2);
  s2 <= s16(3);
  s4 <= s16(4);
  s6 <= s16(5);
  s8 <= s16(6);
  s10 <= s16(7);
  gate2: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s0,
      C => CLK,
      Q => s1);
  gate3: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s2,
      C => CLK,
      Q => s3);
  gate4: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s4,
      C => CLK,
      Q => s5);
  gate5: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s6,
      C => CLK,
      Q => s7);
  gate6: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s8,
      C => CLK,
      Q => s9);
  gate7: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s10,
      C => CLK,
      Q => s11);
  gate8: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s12,
      C => CLK,
      Q => s13);
  gate9: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s14,
      C => CLK,
      Q => s15);
  Output_temp(0) <= s15;
  Output_temp(1) <= s13;
  Output_temp(2) <= s1;
  Output_temp(3) <= s3;
  Output_temp(4) <= s5;
  Output_temp(5) <= s7;
  Output_temp(6) <= s9;
  Output_temp(7) <= s11;
  Output <= Output_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_3 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    out_4: out std_logic;
    out_5: out std_logic;
    out_6: out std_logic;
    out_7: out std_logic;
    sel: in std_logic_vector (2 downto 0) );
end DECODER_3;

architecture Behavioral of DECODER_3 is
begin
  out_0 <= '1' when sel = "000" else '0';
  out_1 <= '1' when sel = "001" else '0';
  out_2 <= '1' when sel = "010" else '0';
  out_3 <= '1' when sel = "011" else '0';
  out_4 <= '1' when sel = "100" else '0';
  out_5 <= '1' when sel = "101" else '0';
  out_6 <= '1' when sel = "110" else '0';
  out_7 <= '1' when sel = "111" else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8_bit is
  port (
    CLK: in std_logic;
    Input: in std_logic_vector(7 downto 0);
    CTRL: in std_logic_vector(1 downto 0); -- 00-> Load
                                           -- 01-> Store
                                           -- 10-> Clear
                                           -- 11-> Set FF
    Output: out std_logic_vector(7 downto 0));
end n8_bit;

architecture Behavioral of n8_bit is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic_vector(7 downto 0);
  signal Output_temp: std_logic_vector(7 downto 0);
begin
  gate0: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => CTRL,
      in_0 => Output_temp,
      in_1 => Input,
      in_2 => "00000000",
      in_3 => "11111111",
      p_out => s16);
  s14 <= s16(0);
  s12 <= s16(1);
  s0 <= s16(2);
  s2 <= s16(3);
  s4 <= s16(4);
  s6 <= s16(5);
  s8 <= s16(6);
  s10 <= s16(7);
  gate1: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s0,
      C => CLK,
      Q => s1);
  gate2: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s2,
      C => CLK,
      Q => s3);
  gate3: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s4,
      C => CLK,
      Q => s5);
  gate4: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s6,
      C => CLK,
      Q => s7);
  gate5: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s8,
      C => CLK,
      Q => s9);
  gate6: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s10,
      C => CLK,
      Q => s11);
  gate7: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s12,
      C => CLK,
      Q => s13);
  gate8: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s14,
      C => CLK,
      Q => s15);
  Output_temp(0) <= s15;
  Output_temp(1) <= s13;
  Output_temp(2) <= s1;
  Output_temp(3) <= s3;
  Output_temp(4) <= s5;
  Output_temp(5) <= s7;
  Output_temp(6) <= s9;
  Output_temp(7) <= s11;
  Output <= Output_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_3 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (2 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0);
    in_4: in std_logic_vector ((Bits-1) downto 0);
    in_5: in std_logic_vector ((Bits-1) downto 0);
    in_6: in std_logic_vector ((Bits-1) downto 0);
    in_7: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_3;

architecture Behavioral of MUX_GATE_BUS_3 is
begin
  with sel select
    p_out <=
      in_0 when "000",
      in_1 when "001",
      in_2 when "010",
      in_3 when "011",
      in_4 when "100",
      in_5 when "101",
      in_6 when "110",
      in_7 when "111",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8B_Memory is
  port (
    Address_pin: in std_logic_vector(2 downto 0);
    clk: in std_logic;
    Data_input: in std_logic_vector(7 downto 0);
    CTRL: in std_logic_vector(1 downto 0);
    Data_output: out std_logic_vector(7 downto 0));
end n8B_Memory;

architecture Behavioral of n8B_Memory is
  signal s0: std_logic;
  signal s1: std_logic_vector(7 downto 0);
  signal s2: std_logic;
  signal s3: std_logic_vector(7 downto 0);
  signal s4: std_logic;
  signal s5: std_logic_vector(7 downto 0);
  signal s6: std_logic;
  signal s7: std_logic_vector(7 downto 0);
  signal s8: std_logic;
  signal s9: std_logic_vector(7 downto 0);
  signal s10: std_logic;
  signal s11: std_logic_vector(7 downto 0);
  signal s12: std_logic;
  signal s13: std_logic_vector(7 downto 0);
  signal s14: std_logic;
  signal s15: std_logic_vector(7 downto 0);
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
begin
  gate0: entity work.DECODER_3
    port map (
      sel => Address_pin,
      out_0 => s16,
      out_1 => s17,
      out_2 => s18,
      out_3 => s19,
      out_4 => s20,
      out_5 => s21,
      out_6 => s22,
      out_7 => s23);
  s10 <= (clk AND s16);
  s12 <= (clk AND s17);
  s14 <= (clk AND s18);
  s0 <= (clk AND s19);
  s2 <= (clk AND s20);
  s4 <= (clk AND s21);
  s6 <= (clk AND s22);
  s8 <= (clk AND s23);
  gate1: entity work.n8_bit
    port map (
      CLK => s0,
      Input => Data_input,
      CTRL => CTRL,
      Output => s1);
  gate2: entity work.n8_bit
    port map (
      CLK => s2,
      Input => Data_input,
      CTRL => CTRL,
      Output => s3);
  gate3: entity work.n8_bit
    port map (
      CLK => s4,
      Input => Data_input,
      CTRL => CTRL,
      Output => s5);
  gate4: entity work.n8_bit
    port map (
      CLK => s6,
      Input => Data_input,
      CTRL => CTRL,
      Output => s7);
  gate5: entity work.n8_bit
    port map (
      CLK => s8,
      Input => Data_input,
      CTRL => CTRL,
      Output => s9);
  gate6: entity work.n8_bit
    port map (
      CLK => s10,
      Input => Data_input,
      CTRL => CTRL,
      Output => s11);
  gate7: entity work.n8_bit
    port map (
      CLK => s12,
      Input => Data_input,
      CTRL => CTRL,
      Output => s13);
  gate8: entity work.n8_bit
    port map (
      CLK => s14,
      Input => Data_input,
      CTRL => CTRL,
      Output => s15);
  gate9: entity work.MUX_GATE_BUS_3
    generic map (
      Bits => 8)
    port map (
      sel => Address_pin,
      in_0 => s11,
      in_1 => s13,
      in_2 => s15,
      in_3 => s1,
      in_4 => s3,
      in_5 => s5,
      in_6 => s7,
      in_7 => s9,
      p_out => Data_output);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8_bit_IR is
  port (
    CLK: in std_logic;
    Input: in std_logic_vector(7 downto 0);
    CTRL: in std_logic_vector(1 downto 0); -- 00-> Load
                                           -- 01-> Store
                                           -- 10-> Clear
                                           -- 11-> Set FF
    Output: out std_logic_vector(7 downto 0));
end n8_bit_IR;

architecture Behavioral of n8_bit_IR is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic_vector(7 downto 0);
  signal Output_temp: std_logic_vector(7 downto 0);
begin
  gate0: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => CTRL,
      in_0 => Output_temp,
      in_1 => Input,
      in_2 => "00000000",
      in_3 => "11111111",
      p_out => s16);
  s14 <= s16(0);
  s12 <= s16(1);
  s0 <= s16(2);
  s2 <= s16(3);
  s4 <= s16(4);
  s6 <= s16(5);
  s8 <= s16(6);
  s10 <= s16(7);
  gate1: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s0,
      C => CLK,
      Q => s1);
  gate2: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s2,
      C => CLK,
      Q => s3);
  gate3: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s4,
      C => CLK,
      Q => s5);
  gate4: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s6,
      C => CLK,
      Q => s7);
  gate5: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s8,
      C => CLK,
      Q => s9);
  gate6: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s10,
      C => CLK,
      Q => s11);
  gate7: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s12,
      C => CLK,
      Q => s13);
  gate8: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s14,
      C => CLK,
      Q => s15);
  Output_temp(0) <= s15;
  Output_temp(1) <= s13;
  Output_temp(2) <= s1;
  Output_temp(3) <= s3;
  Output_temp(4) <= s5;
  Output_temp(5) <= s7;
  Output_temp(6) <= s9;
  Output_temp(7) <= s11;
  Output <= Output_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity DEMUX_GATE_BUS_2 is
  generic (
    Bits : integer;
    Default : integer );
  port (
    out_0: out std_logic_vector ((Bits-1) downto 0);
    out_1: out std_logic_vector ((Bits-1) downto 0);
    out_2: out std_logic_vector ((Bits-1) downto 0);
    out_3: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    p_in: in std_logic_vector ((Bits-1) downto 0) );
end DEMUX_GATE_BUS_2;

architecture Behavioral of DEMUX_GATE_BUS_2 is
begin
    out_0 <= p_in when sel = "00" else std_logic_vector(to_unsigned(Default, Bits));
    out_1 <= p_in when sel = "01" else std_logic_vector(to_unsigned(Default, Bits));
    out_2 <= p_in when sel = "10" else std_logic_vector(to_unsigned(Default, Bits));
    out_3 <= p_in when sel = "11" else std_logic_vector(to_unsigned(Default, Bits));
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity RegisterFile is
  port (
    clk: in std_logic;
    Read_Register1: in std_logic_vector(1 downto 0);
    Read_Register2: in std_logic_vector(1 downto 0);
    Write_data: in std_logic_vector(7 downto 0);
    Write_Register: in std_logic_vector(1 downto 0);
    ctrl: in std_logic_vector(7 downto 0);
    Read_Data1: out std_logic_vector(7 downto 0);
    Read_Data2: out std_logic_vector(7 downto 0));
end RegisterFile;

architecture Behavioral of RegisterFile is
  signal s0: std_logic_vector(7 downto 0);
  signal s1: std_logic_vector(1 downto 0);
  signal s2: std_logic_vector(7 downto 0);
  signal s3: std_logic_vector(7 downto 0);
  signal s4: std_logic_vector(1 downto 0);
  signal s5: std_logic_vector(7 downto 0);
  signal s6: std_logic_vector(7 downto 0);
  signal s7: std_logic_vector(1 downto 0);
  signal s8: std_logic_vector(7 downto 0);
  signal s9: std_logic_vector(7 downto 0);
  signal s10: std_logic_vector(1 downto 0);
  signal s11: std_logic_vector(7 downto 0);
begin
  gate0: entity work.DEMUX_GATE_BUS_2
    generic map (
      Bits => 8,
      Default => 0)
    port map (
      sel => Write_Register,
      p_in => Write_data,
      out_0 => s0,
      out_1 => s3,
      out_2 => s6,
      out_3 => s9);
  s1 <= ctrl(1 downto 0);
  s4 <= ctrl(3 downto 2);
  s7 <= ctrl(5 downto 4);
  s10 <= ctrl(7 downto 6);
  gate1: entity work.n8_bit -- R0
    port map (
      CLK => clk,
      Input => s0,
      CTRL => s1,
      Output => s2);
  gate2: entity work.n8_bit -- R1
    port map (
      CLK => clk,
      Input => s3,
      CTRL => s4,
      Output => s5);
  gate3: entity work.n8_bit -- R2
    port map (
      CLK => clk,
      Input => s6,
      CTRL => s7,
      Output => s8);
  gate4: entity work.n8_bit -- R3
    port map (
      CLK => clk,
      Input => s9,
      CTRL => s10,
      Output => s11);
  gate5: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => Read_Register1,
      in_0 => s2,
      in_1 => s5,
      in_2 => s8,
      in_3 => s11,
      p_out => Read_Data1);
  gate6: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => Read_Register2,
      in_0 => s2,
      in_1 => s5,
      in_2 => s8,
      in_3 => s11,
      p_out => Read_Data2);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8bitAdder2026 is
  port (
    A: in std_logic_vector(7 downto 0);
    Y: in std_logic_vector(7 downto 0);
    Carry_in: in std_logic;
    Carry_out: out std_logic;
    Sum: out std_logic_vector(7 downto 0));
end n8bitAdder2026;

architecture Behavioral of n8bitAdder2026 is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
begin
  s17 <= A(0);
  s13 <= A(1);
  s9 <= A(2);
  s5 <= A(3);
  s0 <= A(4);
  s28 <= A(5);
  s24 <= A(6);
  s20 <= A(7);
  s18 <= Y(0);
  s14 <= Y(1);
  s10 <= Y(2);
  s6 <= Y(3);
  s1 <= Y(4);
  s29 <= Y(5);
  s25 <= Y(6);
  s21 <= Y(7);
  gate0: entity work.n1_bit_full_adder
    port map (
      A => s17,
      B => s18,
      C => Carry_in,
      sum => s19,
      Carry_out => s15);
  gate1: entity work.n1_bit_full_adder
    port map (
      A => s13,
      B => s14,
      C => s15,
      sum => s16,
      Carry_out => s11);
  gate2: entity work.n1_bit_full_adder
    port map (
      A => s9,
      B => s10,
      C => s11,
      sum => s12,
      Carry_out => s7);
  gate3: entity work.n1_bit_full_adder
    port map (
      A => s5,
      B => s6,
      C => s7,
      sum => s8,
      Carry_out => s2);
  gate4: entity work.n1_bit_full_adder
    port map (
      A => s0,
      B => s1,
      C => s2,
      sum => s3,
      Carry_out => s4);
  gate5: entity work.n1_bit_full_adder
    port map (
      A => s28,
      B => s29,
      C => s4,
      sum => s30,
      Carry_out => s26);
  gate6: entity work.n1_bit_full_adder
    port map (
      A => s24,
      B => s25,
      C => s26,
      sum => s27,
      Carry_out => s22);
  gate7: entity work.n1_bit_full_adder
    port map (
      A => s20,
      B => s21,
      C => s22,
      sum => s23,
      Carry_out => Carry_out);
  Sum(0) <= s19;
  Sum(1) <= s16;
  Sum(2) <= s12;
  Sum(3) <= s8;
  Sum(4) <= s3;
  Sum(5) <= s30;
  Sum(6) <= s27;
  Sum(7) <= s23;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8bitALU is
  port (
    A: in std_logic_vector(7 downto 0);
    S_1_S_0_Carry_in: in std_logic_vector(2 downto 0);
    B: in std_logic_vector(7 downto 0);
    Output: out std_logic_vector(7 downto 0);
    Status: out std_logic);
end n8bitALU;

architecture Behavioral of n8bitALU is
  signal s0: std_logic_vector(7 downto 0);
  signal s1: std_logic;
  signal s2: std_logic_vector(1 downto 0);
  signal s3: std_logic_vector(7 downto 0);
  signal const8b0: std_logic_vector(7 downto 0);
  signal s4: std_logic_vector(7 downto 0);
begin
  const8b0 <= "00000000";
  s3 <= NOT B;
  s4 <= NOT const8b0;
  s1 <= S_1_S_0_Carry_in(0);
  s2 <= S_1_S_0_Carry_in(2 downto 1);
  gate0: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => s2,
      in_0 => B,
      in_1 => s3,
      in_2 => const8b0,
      in_3 => s4,
      p_out => s0);
  gate1: entity work.n8bitAdder2026
    port map (
      A => A,
      Y => s0,
      Carry_in => s1,
      Carry_out => Status,
      Sum => Output);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    clk: in std_logic;
    InstrMem_input: in std_logic_vector(7 downto 0);
    InstrMem_ctrl: in std_logic_vector(1 downto 0);
    IR_output: out std_logic_vector(7 downto 0);
    Inst_Fetch: out std_logic;
    Inst_decode: out std_logic;
    Inst_exec: out std_logic;
    Write_Back: out std_logic;
    Program_Counter: out std_logic_vector(2 downto 0);
    IR_ctrl: out std_logic_vector(1 downto 0);
    RegFile_ctrl: out std_logic_vector(7 downto 0);
    ALU_output: out std_logic_vector(7 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(1 downto 0);
  signal s1: std_logic_vector(1 downto 0);
  signal ALU_output_temp: std_logic_vector(7 downto 0);
  signal RegFile_ctrl_temp: std_logic_vector(7 downto 0);
  signal s2: std_logic_vector(7 downto 0);
  signal s3: std_logic_vector(7 downto 0);
  signal s4: std_logic_vector(7 downto 0);
  signal s5: std_logic_vector(2 downto 0);
  signal Program_Counter_temp: std_logic_vector(2 downto 0);
  signal s6: std_logic_vector(7 downto 0);
  signal s7: std_logic_vector(1 downto 0);
  signal s8: std_logic_vector(7 downto 0);
  signal IR_ctrl_temp: std_logic_vector(1 downto 0);
  signal IR_output_temp: std_logic_vector(7 downto 0);
  signal s9: std_logic;
  signal Inst_Fetch_temp: std_logic;
  signal Write_Back_temp: std_logic;
  signal s10: std_logic;
  signal s11: std_logic_vector(7 downto 0);
  signal s12: std_logic_vector(7 downto 0);
  signal s13: std_logic;
begin
  gate0: entity work.ControlUnit
    port map (
      clk => clk,
      Inst_Fetch => Inst_Fetch_temp,
      Inst_Decode => Inst_decode,
      Inst_Execute => Inst_exec,
      Write_back => Write_Back_temp);
  s13 <= InstrMem_ctrl(0);
  s7(0) <= Write_Back_temp;
  s7(1) <= '0';
  gate1: entity work.MUX_GATE_1
    port map (
      sel => s13,
      in_0 => Inst_Fetch_temp,
      in_1 => '0',
      p_out => s10);
  gate2: entity work.n8bit_PC
    port map (
      CLK => clk,
      Inc_by => "00000001",
      CTRL => s7,
      Output => s8);
  IR_ctrl_temp(0) <= s10;
  IR_ctrl_temp(1) <= '0';
  Program_Counter_temp <= s8(2 downto 0);
  gate3: entity work.n8B_Memory
    port map (
      Address_pin => Program_Counter_temp,
      clk => clk,
      Data_input => InstrMem_input,
      CTRL => InstrMem_ctrl,
      Data_output => s6);
  gate4: entity work.n8_bit_IR
    port map (
      CLK => clk,
      Input => s6,
      CTRL => IR_ctrl_temp,
      Output => IR_output_temp);
  s9 <= IR_output_temp(0);
  s1 <= IR_output_temp(2 downto 1);
  s0 <= IR_output_temp(4 downto 3);
  s5 <= IR_output_temp(7 downto 5);
  gate5: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => s0,
      in_0 => "00000001",
      in_1 => "00000100",
      in_2 => "00010000",
      in_3 => "01000000",
      p_out => s11);
  s12(1 downto 0) <= s1;
  s12(7 downto 2) <= "000000";
  gate6: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => Write_Back_temp,
      in_0 => "00000000",
      in_1 => s11,
      p_out => RegFile_ctrl_temp);
  gate7: entity work.RegisterFile
    port map (
      clk => clk,
      Read_Register1 => s0,
      Read_Register2 => s1,
      Write_data => ALU_output_temp,
      Write_Register => s0,
      ctrl => RegFile_ctrl_temp,
      Read_Data1 => s2,
      Read_Data2 => s3);
  gate8: entity work.n8bitALU
    port map (
      A => s4,
      S_1_S_0_Carry_in => s5,
      B => s3,
      Output => ALU_output_temp);
  gate9: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s9,
      in_0 => s2,
      in_1 => s12,
      p_out => s4);
  IR_output <= IR_output_temp;
  Inst_Fetch <= Inst_Fetch_temp;
  Write_Back <= Write_Back_temp;
  Program_Counter <= Program_Counter_temp;
  IR_ctrl <= IR_ctrl_temp;
  RegFile_ctrl <= RegFile_ctrl_temp;
  ALU_output <= ALU_output_temp;
end Behavioral;
